#!/bin/bash
# D T FreeDNSUpdater
# Simple DNS Updater for FreeDNS
#  use script to update dynamic-dns from FreeDNS http://freedns.afraid.org/
# by: Mike Redd
VER=0.1.1

#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                    Version 2, December 2004
#
# Copyright (C) 2011 Mike Redd <mredd@0tue0.com>
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.


# Script uses:
# WGet - http://www.gnu.org/software/wget/

# Checks

if [[ -z $( type -p wget ) ]]; then
    echo -e "wget -- NOT INSTALLED !";exit
fi

# Variables
# RC File - edit with domain and hashed login / pass
DTFREEDNSUPDATERRC="$HOME/.config/dtfreednsupdaterrc"
# Domain - Grabbed from rc file | The Domain you want to update
DOMAIN=`cat $DTFREEDNSUPDATERRC|grep DOMAIN|cut -f 2 -d '"'`
# Log/Pass - Grabbed from rc file. | The hashed login / password provided by FreeDNS
LOGPASS=`cat $DTFREEDNSUPDATERRC|grep LOGPASS|cut -f 2 -d '"'`

# find your ip
YOURIP="$(wget -q -O - api.myiptest.com | awk -F"\"" '{print $4}')"
# file to save ip to for checking
_MYIP="/var/log/myip.txt"
# run
echo -e "DT FreeDNSUpdater $VER"
echo -e "Your IP is $YOURIP"
#
MYIP="$(cat $_MYIP)"
echo -e "$DOMAIN has IP $MYIP"
sleep 1
if [ "$MYIP" != "$YOURIP" ];then
    echo -e "$YOURIP" > $_MYIP
    echo "DNS Needs to be Updated."
    echo "starting update now..."
    sleep 1
    wget -q --read-timeout=0.0 --waitretry=5 --tries=400 --background http://freedns.afraid.org/dynamic/update.php?$LOGPASS
    sleep 1
    echo "dns updated..."
    echo -e "$DOMAIN has $MYIP)"
else
    echo "DNS does not need an update."
fi

