#!/bin/bash
# D T FreeDNSUpdater
# Simple DNS Updater for FreeDNS
#  use script to update dynamic-dns from FreeDNS http://freedns.afraid.org/
# by: Mike Redd
VER=0.1.4
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                    Version 2, December 2004
#
# Copyright (C) 2011 Mike Redd <mredd@0tue0.com>
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.


# Script uses:
# WGet - http://www.gnu.org/software/wget/

# Checks

if [[ -z $( type -p wget ) ]]; then
    echo -e "wget -- NOT INSTALLED !";exit
fi

# Variables
USER="/home/mredd"
# RC File - edit with domain and hashed login / pass
DTFREEDNSUPDATERRC="$USER/.config/dtfreednsupdaterrc"
# Domain - Grabbed from rc file | The Domain you want to update
DOMAINONE=`cat $DTFREEDNSUPDATERRC|grep DOMAINONE|cut -f 2 -d '"'`
# Log/Pass - Grabbed from rc file. | The hashed login / password provided by FreeDNS
LOGPASSONE=`cat $DTFREEDNSUPDATERRC|grep LOGPASSONE|cut -f 2 -d '"'`
# Domain - Grabbed from rc file | The Domain you want to update
DOMAINTWO=`cat $DTFREEDNSUPDATERRC|grep DOMAINTWO|cut -f 2 -d '"'`
# Log/Pass - Grabbed from rc file. | The hashed login / password provided by FreeDNS
LOGPASSTWO=`cat $DTFREEDNSUPDATERRC|grep LOGPASSTWO|cut -f 2 -d '"'`

# find your ip
YOURIP="$(wget -q -O - api.myiptest.com | awk -F"\"" '{print $4}')"
# file to save ip to for checking
LOGIP="$USER/tmp/log/myip.txt"
# run
if [ "$DOMAINONE" == "CHANGEME" ];then
    echo -e " - DT FreeDNSUpdater V.$VER -"
    echo " Please Edit dtfreednsypdaterrc With Your Domain and Restart App"
    exit
elif [ "$LOGPASSONE" == "CHANGEME" ];then
    echo -e " - DT FreeDNSUpdater V.$VER -"
    echo " Please Edit dtfreednsypdaterrc With Your Hashed Log Pass and Restart App"
    exit
else
echo -e " - DT FreeDNSUpdater V.$VER -"
echo -e " Your IP is $YOURIP"
#
MYIP="$(cat $LOGIP|tr -d " ")"
echo -e " $DOMAINONE IP $MYIP"
sleep 1
if [ "$MYIP" != "$YOURIP" ];then
    echo -e " $YOURIP" > $LOGIP
    echo " DNS Needs to be Updated."
    echo " Starting Update Now..."
    sleep 1
    wget -q --read-timeout=0.0 --waitretry=5 --tries=400 --background http://freedns.afraid.org/dynamic/update.php?$LOGPASSONE
    sleep 1
    echo " DNS Updated..."
    echo -e " $DOMAIN has $MYIP"
else
    sleep 1
    echo
    echo " Your DNS does not need an update."
    echo
fi
fi

# find your ip
YOURIP="$(wget -q -O - api.myiptest.com | awk -F"\"" '{print $4}')"
# file to save ip to for checking
LOGIP="/var/log/myip.txt"
# run
if [ "$DOMAINTWO" == "CHANGEME" ];then
    echo -e " - DT FreeDNSUpdater V.$VER -"
    echo " Please Edit dtfreednsypdaterrc With Your Domain and Restart App"
    exit
elif [ "$LOGPASSTWO" == "CHANGEME" ];then
    echo -e " - DT FreeDNSUpdater V.$VER -"
    echo " Please Edit dtfreednsypdaterrc With Your Hashed Log Pass and Restart App"
    exit
else
echo -e " - DT FreeDNSUpdater V.$VER -"
echo -e " Your IP is $YOURIP"
#
#MYIP="$(cat $LOGIP|tr -d " ")"
echo -e " $DOMAINTWO IP $MYIP"
sleep 1
if [ "$MYIP" != "$YOURIP" ];then
    echo -e " $YOURIP" > $LOGIP
    echo " DNS Needs to be Updated."
    echo " Starting Update Now..."
    sleep 1
    wget -q --read-timeout=0.0 --waitretry=5 --tries=400 --background http://freedns.afraid.org/dynamic/update.php?$LOGPASSTWO
    sleep 1
    echo " DNS Updated..."
    echo -e " $DOMAINTWO has $MYIP"
else
    sleep 1
    echo
    echo " Your DNS does not need an update."
    echo
fi
fi
